# Generated by Django 5.1.4 on 2026-09-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("awarding_body", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="awards/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-year", "order"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("book", "Book Publication"),
                            ("lecture", "Guest Talk / Lecture"),
                            ("evaluation", "Academic Evaluation"),
                            ("conference", "Conference Chair"),
                            ("fdp", "Faculty Refresher"),
                            ("workshop", "AI Workshop"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-event_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=300)),
                ("university", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("alternate_email", models.EmailField(blank=True, max_length=254)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("short_intro", models.TextField()),
                ("biography", models.TextField()),
                ("research_vision", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField()),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("book", "Book Chapter"),
                            ("book", "Book"),
                            ("other", "Other"),
                        ],
                        default="journal",
                        max_length=50,
                    ),
                ),
                ("journal_or_venue", models.CharField(blank=True, max_length=500)),
                ("publication_year", models.PositiveIntegerField()),
                ("doi", models.URLField(blank=True, null=True)),
                ("scopus_indexed", models.BooleanField(default=False)),
                ("citation_count", models.PositiveIntegerField(default=0)),
                ("abstract", models.TextField(blank=True)),
                ("is_top_publication", models.BooleanField(default=False)),
                ("is_recent", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-publication_year"],
            },
        ),
        migrations.CreateModel(
            name="ResearchArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchTrajectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("organizer", models.CharField(blank=True, max_length=300)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "certificate",
                    models.ImageField(blank=True, null=True, upload_to="training/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/gallery/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="myapp.event",
                    ),
                ),
            ],
        ),
    ]
